import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      hello
    </html>
  )
}

/*Layout it is a parent component that is used by other pages, so whatever we write here it is going to apply for all pages */
 
/****We can create differente layout for different routes */